# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haidir/project/EmulatorProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haidir/project/EmulatorProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haidir/project/EmulatorProject/CMakeFiles /home/haidir/project/EmulatorProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haidir/project/EmulatorProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named h

# Build rule for target.
h : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 h
.PHONY : h

# fast build rule for target.
h/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/build
.PHONY : h/fast

#=============================================================================
# Target rules for targets named hc

# Build rule for target.
hc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hc
.PHONY : hc

# fast build rule for target.
hc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/build
.PHONY : hc/fast

hcompiler.o: hcompiler.cpp.o
.PHONY : hcompiler.o

# target to build an object file
hcompiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/hcompiler.cpp.o
.PHONY : hcompiler.cpp.o

hcompiler.i: hcompiler.cpp.i
.PHONY : hcompiler.i

# target to preprocess a source file
hcompiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/hcompiler.cpp.i
.PHONY : hcompiler.cpp.i

hcompiler.s: hcompiler.cpp.s
.PHONY : hcompiler.s

# target to generate assembly for a file
hcompiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/hcompiler.cpp.s
.PHONY : hcompiler.cpp.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/main.c.s
.PHONY : main.c.s

src/cpp/file_reader.o: src/cpp/file_reader.cpp.o
.PHONY : src/cpp/file_reader.o

# target to build an object file
src/cpp/file_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/file_reader.cpp.o
.PHONY : src/cpp/file_reader.cpp.o

src/cpp/file_reader.i: src/cpp/file_reader.cpp.i
.PHONY : src/cpp/file_reader.i

# target to preprocess a source file
src/cpp/file_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/file_reader.cpp.i
.PHONY : src/cpp/file_reader.cpp.i

src/cpp/file_reader.s: src/cpp/file_reader.cpp.s
.PHONY : src/cpp/file_reader.s

# target to generate assembly for a file
src/cpp/file_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/file_reader.cpp.s
.PHONY : src/cpp/file_reader.cpp.s

src/cpp/ins.compiler.o: src/cpp/ins.compiler.cpp.o
.PHONY : src/cpp/ins.compiler.o

# target to build an object file
src/cpp/ins.compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins.compiler.cpp.o
.PHONY : src/cpp/ins.compiler.cpp.o

src/cpp/ins.compiler.i: src/cpp/ins.compiler.cpp.i
.PHONY : src/cpp/ins.compiler.i

# target to preprocess a source file
src/cpp/ins.compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins.compiler.cpp.i
.PHONY : src/cpp/ins.compiler.cpp.i

src/cpp/ins.compiler.s: src/cpp/ins.compiler.cpp.s
.PHONY : src/cpp/ins.compiler.s

# target to generate assembly for a file
src/cpp/ins.compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins.compiler.cpp.s
.PHONY : src/cpp/ins.compiler.cpp.s

src/cpp/ins_make.o: src/cpp/ins_make.cpp.o
.PHONY : src/cpp/ins_make.o

# target to build an object file
src/cpp/ins_make.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_make.cpp.o
.PHONY : src/cpp/ins_make.cpp.o

src/cpp/ins_make.i: src/cpp/ins_make.cpp.i
.PHONY : src/cpp/ins_make.i

# target to preprocess a source file
src/cpp/ins_make.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_make.cpp.i
.PHONY : src/cpp/ins_make.cpp.i

src/cpp/ins_make.s: src/cpp/ins_make.cpp.s
.PHONY : src/cpp/ins_make.s

# target to generate assembly for a file
src/cpp/ins_make.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_make.cpp.s
.PHONY : src/cpp/ins_make.cpp.s

src/cpp/ins_tools.o: src/cpp/ins_tools.cpp.o
.PHONY : src/cpp/ins_tools.o

# target to build an object file
src/cpp/ins_tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_tools.cpp.o
.PHONY : src/cpp/ins_tools.cpp.o

src/cpp/ins_tools.i: src/cpp/ins_tools.cpp.i
.PHONY : src/cpp/ins_tools.i

# target to preprocess a source file
src/cpp/ins_tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_tools.cpp.i
.PHONY : src/cpp/ins_tools.cpp.i

src/cpp/ins_tools.s: src/cpp/ins_tools.cpp.s
.PHONY : src/cpp/ins_tools.s

# target to generate assembly for a file
src/cpp/ins_tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/ins_tools.cpp.s
.PHONY : src/cpp/ins_tools.cpp.s

src/cpp/instruction.o: src/cpp/instruction.cpp.o
.PHONY : src/cpp/instruction.o

# target to build an object file
src/cpp/instruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/instruction.cpp.o
.PHONY : src/cpp/instruction.cpp.o

src/cpp/instruction.i: src/cpp/instruction.cpp.i
.PHONY : src/cpp/instruction.i

# target to preprocess a source file
src/cpp/instruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/instruction.cpp.i
.PHONY : src/cpp/instruction.cpp.i

src/cpp/instruction.s: src/cpp/instruction.cpp.s
.PHONY : src/cpp/instruction.s

# target to generate assembly for a file
src/cpp/instruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/instruction.cpp.s
.PHONY : src/cpp/instruction.cpp.s

src/cpp/label.o: src/cpp/label.cpp.o
.PHONY : src/cpp/label.o

# target to build an object file
src/cpp/label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/label.cpp.o
.PHONY : src/cpp/label.cpp.o

src/cpp/label.i: src/cpp/label.cpp.i
.PHONY : src/cpp/label.i

# target to preprocess a source file
src/cpp/label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/label.cpp.i
.PHONY : src/cpp/label.cpp.i

src/cpp/label.s: src/cpp/label.cpp.s
.PHONY : src/cpp/label.s

# target to generate assembly for a file
src/cpp/label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/label.cpp.s
.PHONY : src/cpp/label.cpp.s

src/cpp/tools.o: src/cpp/tools.cpp.o
.PHONY : src/cpp/tools.o

# target to build an object file
src/cpp/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/tools.cpp.o
.PHONY : src/cpp/tools.cpp.o

src/cpp/tools.i: src/cpp/tools.cpp.i
.PHONY : src/cpp/tools.i

# target to preprocess a source file
src/cpp/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/tools.cpp.i
.PHONY : src/cpp/tools.cpp.i

src/cpp/tools.s: src/cpp/tools.cpp.s
.PHONY : src/cpp/tools.s

# target to generate assembly for a file
src/cpp/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/cpp/tools.cpp.s
.PHONY : src/cpp/tools.cpp.s

src/cpu.o: src/cpu.c.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/cpu.c.o
.PHONY : src/cpu.c.o

src/cpu.i: src/cpu.c.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/cpu.c.i
.PHONY : src/cpu.c.i

src/cpu.s: src/cpu.c.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/cpu.c.s
.PHONY : src/cpu.c.s

src/data/ascii.o: src/data/ascii.cpp.o
.PHONY : src/data/ascii.o

# target to build an object file
src/data/ascii.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/ascii.cpp.o
.PHONY : src/data/ascii.cpp.o

src/data/ascii.i: src/data/ascii.cpp.i
.PHONY : src/data/ascii.i

# target to preprocess a source file
src/data/ascii.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/ascii.cpp.i
.PHONY : src/data/ascii.cpp.i

src/data/ascii.s: src/data/ascii.cpp.s
.PHONY : src/data/ascii.s

# target to generate assembly for a file
src/data/ascii.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/ascii.cpp.s
.PHONY : src/data/ascii.cpp.s

src/data/datatype.o: src/data/datatype.cpp.o
.PHONY : src/data/datatype.o

# target to build an object file
src/data/datatype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/datatype.cpp.o
.PHONY : src/data/datatype.cpp.o

src/data/datatype.i: src/data/datatype.cpp.i
.PHONY : src/data/datatype.i

# target to preprocess a source file
src/data/datatype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/datatype.cpp.i
.PHONY : src/data/datatype.cpp.i

src/data/datatype.s: src/data/datatype.cpp.s
.PHONY : src/data/datatype.s

# target to generate assembly for a file
src/data/datatype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/data/datatype.cpp.s
.PHONY : src/data/datatype.cpp.s

src/file_reader.o: src/file_reader.c.o
.PHONY : src/file_reader.o

# target to build an object file
src/file_reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/file_reader.c.o
.PHONY : src/file_reader.c.o

src/file_reader.i: src/file_reader.c.i
.PHONY : src/file_reader.i

# target to preprocess a source file
src/file_reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/file_reader.c.i
.PHONY : src/file_reader.c.i

src/file_reader.s: src/file_reader.c.s
.PHONY : src/file_reader.s

# target to generate assembly for a file
src/file_reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/file_reader.c.s
.PHONY : src/file_reader.c.s

src/ins/add.o: src/ins/add.c.o
.PHONY : src/ins/add.o

# target to build an object file
src/ins/add.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/add.c.o
.PHONY : src/ins/add.c.o

src/ins/add.i: src/ins/add.c.i
.PHONY : src/ins/add.i

# target to preprocess a source file
src/ins/add.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/add.c.i
.PHONY : src/ins/add.c.i

src/ins/add.s: src/ins/add.c.s
.PHONY : src/ins/add.s

# target to generate assembly for a file
src/ins/add.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/add.c.s
.PHONY : src/ins/add.c.s

src/ins/and.o: src/ins/and.c.o
.PHONY : src/ins/and.o

# target to build an object file
src/ins/and.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/and.c.o
.PHONY : src/ins/and.c.o

src/ins/and.i: src/ins/and.c.i
.PHONY : src/ins/and.i

# target to preprocess a source file
src/ins/and.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/and.c.i
.PHONY : src/ins/and.c.i

src/ins/and.s: src/ins/and.c.s
.PHONY : src/ins/and.s

# target to generate assembly for a file
src/ins/and.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/and.c.s
.PHONY : src/ins/and.c.s

src/ins/call.o: src/ins/call.c.o
.PHONY : src/ins/call.o

# target to build an object file
src/ins/call.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/call.c.o
.PHONY : src/ins/call.c.o

src/ins/call.i: src/ins/call.c.i
.PHONY : src/ins/call.i

# target to preprocess a source file
src/ins/call.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/call.c.i
.PHONY : src/ins/call.c.i

src/ins/call.s: src/ins/call.c.s
.PHONY : src/ins/call.s

# target to generate assembly for a file
src/ins/call.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/call.c.s
.PHONY : src/ins/call.c.s

src/ins/cnd.o: src/ins/cnd.c.o
.PHONY : src/ins/cnd.o

# target to build an object file
src/ins/cnd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/cnd.c.o
.PHONY : src/ins/cnd.c.o

src/ins/cnd.i: src/ins/cnd.c.i
.PHONY : src/ins/cnd.i

# target to preprocess a source file
src/ins/cnd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/cnd.c.i
.PHONY : src/ins/cnd.c.i

src/ins/cnd.s: src/ins/cnd.c.s
.PHONY : src/ins/cnd.s

# target to generate assembly for a file
src/ins/cnd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/cnd.c.s
.PHONY : src/ins/cnd.c.s

src/ins/div.o: src/ins/div.c.o
.PHONY : src/ins/div.o

# target to build an object file
src/ins/div.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/div.c.o
.PHONY : src/ins/div.c.o

src/ins/div.i: src/ins/div.c.i
.PHONY : src/ins/div.i

# target to preprocess a source file
src/ins/div.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/div.c.i
.PHONY : src/ins/div.c.i

src/ins/div.s: src/ins/div.c.s
.PHONY : src/ins/div.s

# target to generate assembly for a file
src/ins/div.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/div.c.s
.PHONY : src/ins/div.c.s

src/ins/go.o: src/ins/go.c.o
.PHONY : src/ins/go.o

# target to build an object file
src/ins/go.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/go.c.o
.PHONY : src/ins/go.c.o

src/ins/go.i: src/ins/go.c.i
.PHONY : src/ins/go.i

# target to preprocess a source file
src/ins/go.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/go.c.i
.PHONY : src/ins/go.c.i

src/ins/go.s: src/ins/go.c.s
.PHONY : src/ins/go.s

# target to generate assembly for a file
src/ins/go.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/go.c.s
.PHONY : src/ins/go.c.s

src/ins/lod.o: src/ins/lod.c.o
.PHONY : src/ins/lod.o

# target to build an object file
src/ins/lod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/lod.c.o
.PHONY : src/ins/lod.c.o

src/ins/lod.i: src/ins/lod.c.i
.PHONY : src/ins/lod.i

# target to preprocess a source file
src/ins/lod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/lod.c.i
.PHONY : src/ins/lod.c.i

src/ins/lod.s: src/ins/lod.c.s
.PHONY : src/ins/lod.s

# target to generate assembly for a file
src/ins/lod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/lod.c.s
.PHONY : src/ins/lod.c.s

src/ins/mov.o: src/ins/mov.c.o
.PHONY : src/ins/mov.o

# target to build an object file
src/ins/mov.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mov.c.o
.PHONY : src/ins/mov.c.o

src/ins/mov.i: src/ins/mov.c.i
.PHONY : src/ins/mov.i

# target to preprocess a source file
src/ins/mov.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mov.c.i
.PHONY : src/ins/mov.c.i

src/ins/mov.s: src/ins/mov.c.s
.PHONY : src/ins/mov.s

# target to generate assembly for a file
src/ins/mov.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mov.c.s
.PHONY : src/ins/mov.c.s

src/ins/mul.o: src/ins/mul.c.o
.PHONY : src/ins/mul.o

# target to build an object file
src/ins/mul.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mul.c.o
.PHONY : src/ins/mul.c.o

src/ins/mul.i: src/ins/mul.c.i
.PHONY : src/ins/mul.i

# target to preprocess a source file
src/ins/mul.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mul.c.i
.PHONY : src/ins/mul.c.i

src/ins/mul.s: src/ins/mul.c.s
.PHONY : src/ins/mul.s

# target to generate assembly for a file
src/ins/mul.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/mul.c.s
.PHONY : src/ins/mul.c.s

src/ins/nand.o: src/ins/nand.c.o
.PHONY : src/ins/nand.o

# target to build an object file
src/ins/nand.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nand.c.o
.PHONY : src/ins/nand.c.o

src/ins/nand.i: src/ins/nand.c.i
.PHONY : src/ins/nand.i

# target to preprocess a source file
src/ins/nand.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nand.c.i
.PHONY : src/ins/nand.c.i

src/ins/nand.s: src/ins/nand.c.s
.PHONY : src/ins/nand.s

# target to generate assembly for a file
src/ins/nand.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nand.c.s
.PHONY : src/ins/nand.c.s

src/ins/nor.o: src/ins/nor.c.o
.PHONY : src/ins/nor.o

# target to build an object file
src/ins/nor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nor.c.o
.PHONY : src/ins/nor.c.o

src/ins/nor.i: src/ins/nor.c.i
.PHONY : src/ins/nor.i

# target to preprocess a source file
src/ins/nor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nor.c.i
.PHONY : src/ins/nor.c.i

src/ins/nor.s: src/ins/nor.c.s
.PHONY : src/ins/nor.s

# target to generate assembly for a file
src/ins/nor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/nor.c.s
.PHONY : src/ins/nor.c.s

src/ins/not.o: src/ins/not.c.o
.PHONY : src/ins/not.o

# target to build an object file
src/ins/not.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/not.c.o
.PHONY : src/ins/not.c.o

src/ins/not.i: src/ins/not.c.i
.PHONY : src/ins/not.i

# target to preprocess a source file
src/ins/not.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/not.c.i
.PHONY : src/ins/not.c.i

src/ins/not.s: src/ins/not.c.s
.PHONY : src/ins/not.s

# target to generate assembly for a file
src/ins/not.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/not.c.s
.PHONY : src/ins/not.c.s

src/ins/or.o: src/ins/or.c.o
.PHONY : src/ins/or.o

# target to build an object file
src/ins/or.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/or.c.o
.PHONY : src/ins/or.c.o

src/ins/or.i: src/ins/or.c.i
.PHONY : src/ins/or.i

# target to preprocess a source file
src/ins/or.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/or.c.i
.PHONY : src/ins/or.c.i

src/ins/or.s: src/ins/or.c.s
.PHONY : src/ins/or.s

# target to generate assembly for a file
src/ins/or.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/or.c.s
.PHONY : src/ins/or.c.s

src/ins/pct.o: src/ins/pct.c.o
.PHONY : src/ins/pct.o

# target to build an object file
src/ins/pct.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pct.c.o
.PHONY : src/ins/pct.c.o

src/ins/pct.i: src/ins/pct.c.i
.PHONY : src/ins/pct.i

# target to preprocess a source file
src/ins/pct.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pct.c.i
.PHONY : src/ins/pct.c.i

src/ins/pct.s: src/ins/pct.c.s
.PHONY : src/ins/pct.s

# target to generate assembly for a file
src/ins/pct.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pct.c.s
.PHONY : src/ins/pct.c.s

src/ins/pnt.o: src/ins/pnt.c.o
.PHONY : src/ins/pnt.o

# target to build an object file
src/ins/pnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pnt.c.o
.PHONY : src/ins/pnt.c.o

src/ins/pnt.i: src/ins/pnt.c.i
.PHONY : src/ins/pnt.i

# target to preprocess a source file
src/ins/pnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pnt.c.i
.PHONY : src/ins/pnt.c.i

src/ins/pnt.s: src/ins/pnt.c.s
.PHONY : src/ins/pnt.s

# target to generate assembly for a file
src/ins/pnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pnt.c.s
.PHONY : src/ins/pnt.c.s

src/ins/pop.o: src/ins/pop.c.o
.PHONY : src/ins/pop.o

# target to build an object file
src/ins/pop.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pop.c.o
.PHONY : src/ins/pop.c.o

src/ins/pop.i: src/ins/pop.c.i
.PHONY : src/ins/pop.i

# target to preprocess a source file
src/ins/pop.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pop.c.i
.PHONY : src/ins/pop.c.i

src/ins/pop.s: src/ins/pop.c.s
.PHONY : src/ins/pop.s

# target to generate assembly for a file
src/ins/pop.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/pop.c.s
.PHONY : src/ins/pop.c.s

src/ins/push.o: src/ins/push.c.o
.PHONY : src/ins/push.o

# target to build an object file
src/ins/push.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/push.c.o
.PHONY : src/ins/push.c.o

src/ins/push.i: src/ins/push.c.i
.PHONY : src/ins/push.i

# target to preprocess a source file
src/ins/push.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/push.c.i
.PHONY : src/ins/push.c.i

src/ins/push.s: src/ins/push.c.s
.PHONY : src/ins/push.s

# target to generate assembly for a file
src/ins/push.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/push.c.s
.PHONY : src/ins/push.c.s

src/ins/ret.o: src/ins/ret.c.o
.PHONY : src/ins/ret.o

# target to build an object file
src/ins/ret.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/ret.c.o
.PHONY : src/ins/ret.c.o

src/ins/ret.i: src/ins/ret.c.i
.PHONY : src/ins/ret.i

# target to preprocess a source file
src/ins/ret.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/ret.c.i
.PHONY : src/ins/ret.c.i

src/ins/ret.s: src/ins/ret.c.s
.PHONY : src/ins/ret.s

# target to generate assembly for a file
src/ins/ret.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/ret.c.s
.PHONY : src/ins/ret.c.s

src/ins/sh.o: src/ins/sh.c.o
.PHONY : src/ins/sh.o

# target to build an object file
src/ins/sh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sh.c.o
.PHONY : src/ins/sh.c.o

src/ins/sh.i: src/ins/sh.c.i
.PHONY : src/ins/sh.i

# target to preprocess a source file
src/ins/sh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sh.c.i
.PHONY : src/ins/sh.c.i

src/ins/sh.s: src/ins/sh.c.s
.PHONY : src/ins/sh.s

# target to generate assembly for a file
src/ins/sh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sh.c.s
.PHONY : src/ins/sh.c.s

src/ins/stp.o: src/ins/stp.c.o
.PHONY : src/ins/stp.o

# target to build an object file
src/ins/stp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/stp.c.o
.PHONY : src/ins/stp.c.o

src/ins/stp.i: src/ins/stp.c.i
.PHONY : src/ins/stp.i

# target to preprocess a source file
src/ins/stp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/stp.c.i
.PHONY : src/ins/stp.c.i

src/ins/stp.s: src/ins/stp.c.s
.PHONY : src/ins/stp.s

# target to generate assembly for a file
src/ins/stp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/stp.c.s
.PHONY : src/ins/stp.c.s

src/ins/str.o: src/ins/str.c.o
.PHONY : src/ins/str.o

# target to build an object file
src/ins/str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/str.c.o
.PHONY : src/ins/str.c.o

src/ins/str.i: src/ins/str.c.i
.PHONY : src/ins/str.i

# target to preprocess a source file
src/ins/str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/str.c.i
.PHONY : src/ins/str.c.i

src/ins/str.s: src/ins/str.c.s
.PHONY : src/ins/str.s

# target to generate assembly for a file
src/ins/str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/str.c.s
.PHONY : src/ins/str.c.s

src/ins/sub.o: src/ins/sub.c.o
.PHONY : src/ins/sub.o

# target to build an object file
src/ins/sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sub.c.o
.PHONY : src/ins/sub.c.o

src/ins/sub.i: src/ins/sub.c.i
.PHONY : src/ins/sub.i

# target to preprocess a source file
src/ins/sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sub.c.i
.PHONY : src/ins/sub.c.i

src/ins/sub.s: src/ins/sub.c.s
.PHONY : src/ins/sub.s

# target to generate assembly for a file
src/ins/sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/sub.c.s
.PHONY : src/ins/sub.c.s

src/ins/xor.o: src/ins/xor.c.o
.PHONY : src/ins/xor.o

# target to build an object file
src/ins/xor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/xor.c.o
.PHONY : src/ins/xor.c.o

src/ins/xor.i: src/ins/xor.c.i
.PHONY : src/ins/xor.i

# target to preprocess a source file
src/ins/xor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/xor.c.i
.PHONY : src/ins/xor.c.i

src/ins/xor.s: src/ins/xor.c.s
.PHONY : src/ins/xor.s

# target to generate assembly for a file
src/ins/xor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins/xor.c.s
.PHONY : src/ins/xor.c.s

src/ins_make.o: src/ins_make.c.o
.PHONY : src/ins_make.o

# target to build an object file
src/ins_make.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_make.c.o
.PHONY : src/ins_make.c.o

src/ins_make.i: src/ins_make.c.i
.PHONY : src/ins_make.i

# target to preprocess a source file
src/ins_make.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_make.c.i
.PHONY : src/ins_make.c.i

src/ins_make.s: src/ins_make.c.s
.PHONY : src/ins_make.s

# target to generate assembly for a file
src/ins_make.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_make.c.s
.PHONY : src/ins_make.c.s

src/ins_tools.o: src/ins_tools.c.o
.PHONY : src/ins_tools.o

# target to build an object file
src/ins_tools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_tools.c.o
.PHONY : src/ins_tools.c.o

src/ins_tools.i: src/ins_tools.c.i
.PHONY : src/ins_tools.i

# target to preprocess a source file
src/ins_tools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_tools.c.i
.PHONY : src/ins_tools.c.i

src/ins_tools.s: src/ins_tools.c.s
.PHONY : src/ins_tools.s

# target to generate assembly for a file
src/ins_tools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/src/ins_tools.c.s
.PHONY : src/ins_tools.c.s

src/tools/memory.o: src/tools/memory.cpp.o
.PHONY : src/tools/memory.o

# target to build an object file
src/tools/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/tools/memory.cpp.o
.PHONY : src/tools/memory.cpp.o

src/tools/memory.i: src/tools/memory.cpp.i
.PHONY : src/tools/memory.i

# target to preprocess a source file
src/tools/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/tools/memory.cpp.i
.PHONY : src/tools/memory.cpp.i

src/tools/memory.s: src/tools/memory.cpp.s
.PHONY : src/tools/memory.s

# target to generate assembly for a file
src/tools/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hc.dir/build.make CMakeFiles/hc.dir/src/tools/memory.cpp.s
.PHONY : src/tools/memory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... h"
	@echo "... hc"
	@echo "... hcompiler.o"
	@echo "... hcompiler.i"
	@echo "... hcompiler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/cpp/file_reader.o"
	@echo "... src/cpp/file_reader.i"
	@echo "... src/cpp/file_reader.s"
	@echo "... src/cpp/ins.compiler.o"
	@echo "... src/cpp/ins.compiler.i"
	@echo "... src/cpp/ins.compiler.s"
	@echo "... src/cpp/ins_make.o"
	@echo "... src/cpp/ins_make.i"
	@echo "... src/cpp/ins_make.s"
	@echo "... src/cpp/ins_tools.o"
	@echo "... src/cpp/ins_tools.i"
	@echo "... src/cpp/ins_tools.s"
	@echo "... src/cpp/instruction.o"
	@echo "... src/cpp/instruction.i"
	@echo "... src/cpp/instruction.s"
	@echo "... src/cpp/label.o"
	@echo "... src/cpp/label.i"
	@echo "... src/cpp/label.s"
	@echo "... src/cpp/tools.o"
	@echo "... src/cpp/tools.i"
	@echo "... src/cpp/tools.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/data/ascii.o"
	@echo "... src/data/ascii.i"
	@echo "... src/data/ascii.s"
	@echo "... src/data/datatype.o"
	@echo "... src/data/datatype.i"
	@echo "... src/data/datatype.s"
	@echo "... src/file_reader.o"
	@echo "... src/file_reader.i"
	@echo "... src/file_reader.s"
	@echo "... src/ins/add.o"
	@echo "... src/ins/add.i"
	@echo "... src/ins/add.s"
	@echo "... src/ins/and.o"
	@echo "... src/ins/and.i"
	@echo "... src/ins/and.s"
	@echo "... src/ins/call.o"
	@echo "... src/ins/call.i"
	@echo "... src/ins/call.s"
	@echo "... src/ins/cnd.o"
	@echo "... src/ins/cnd.i"
	@echo "... src/ins/cnd.s"
	@echo "... src/ins/div.o"
	@echo "... src/ins/div.i"
	@echo "... src/ins/div.s"
	@echo "... src/ins/go.o"
	@echo "... src/ins/go.i"
	@echo "... src/ins/go.s"
	@echo "... src/ins/lod.o"
	@echo "... src/ins/lod.i"
	@echo "... src/ins/lod.s"
	@echo "... src/ins/mov.o"
	@echo "... src/ins/mov.i"
	@echo "... src/ins/mov.s"
	@echo "... src/ins/mul.o"
	@echo "... src/ins/mul.i"
	@echo "... src/ins/mul.s"
	@echo "... src/ins/nand.o"
	@echo "... src/ins/nand.i"
	@echo "... src/ins/nand.s"
	@echo "... src/ins/nor.o"
	@echo "... src/ins/nor.i"
	@echo "... src/ins/nor.s"
	@echo "... src/ins/not.o"
	@echo "... src/ins/not.i"
	@echo "... src/ins/not.s"
	@echo "... src/ins/or.o"
	@echo "... src/ins/or.i"
	@echo "... src/ins/or.s"
	@echo "... src/ins/pct.o"
	@echo "... src/ins/pct.i"
	@echo "... src/ins/pct.s"
	@echo "... src/ins/pnt.o"
	@echo "... src/ins/pnt.i"
	@echo "... src/ins/pnt.s"
	@echo "... src/ins/pop.o"
	@echo "... src/ins/pop.i"
	@echo "... src/ins/pop.s"
	@echo "... src/ins/push.o"
	@echo "... src/ins/push.i"
	@echo "... src/ins/push.s"
	@echo "... src/ins/ret.o"
	@echo "... src/ins/ret.i"
	@echo "... src/ins/ret.s"
	@echo "... src/ins/sh.o"
	@echo "... src/ins/sh.i"
	@echo "... src/ins/sh.s"
	@echo "... src/ins/stp.o"
	@echo "... src/ins/stp.i"
	@echo "... src/ins/stp.s"
	@echo "... src/ins/str.o"
	@echo "... src/ins/str.i"
	@echo "... src/ins/str.s"
	@echo "... src/ins/sub.o"
	@echo "... src/ins/sub.i"
	@echo "... src/ins/sub.s"
	@echo "... src/ins/xor.o"
	@echo "... src/ins/xor.i"
	@echo "... src/ins/xor.s"
	@echo "... src/ins_make.o"
	@echo "... src/ins_make.i"
	@echo "... src/ins_make.s"
	@echo "... src/ins_tools.o"
	@echo "... src/ins_tools.i"
	@echo "... src/ins_tools.s"
	@echo "... src/tools/memory.o"
	@echo "... src/tools/memory.i"
	@echo "... src/tools/memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

